### PR TITLE
Add startupprobes for jackett and nzbhydra2

### PR DESCRIPTION
**Pull request by onedr0p**
Chart version change:

* jackett: 1.0.2 -> 1.1.0
* nzbhydra2: 1.0.2 -> 1.1.0

> Note: startupprobes is only supported on k8s version 1.16 or higher

Closes https://github.com/billimek/billimek-charts/issues/100

@billimek I will open an issue and PR to implement the rest after this gets merged and tested.

### CODE REVIEW

**Comment by onedr0p** [comment]
A major change is I went with `periodSeconds` over `timeoutSeconds`. It makes more sense to me using that.

**Comment by billimek** [comment]
`startupProbe` wasn't introduced in kubernetes until release v1.16.  I'm not sure what will happen if the chart is attempted to be installed in a kubernetes version earlier than 1.16.  When I [searched](https://github.com/helm/charts/search?q=startupProbe&unscoped_q=startupProbe) the entire helm charts/stable repo, only one instance (influxdb) shows that uses startupProbe, and it's gated with a value to enable it.

What do you think about 'wrapping' the use of `startupProbe` as something that can be optionally enabled via values?

**Comment by onedr0p** [comment]
I can look into that. Too bad we just can't support 1.16+ :)

**Comment by billimek** [comment]
It's interesting: the chart testing circleCI job is installing and running kubernetes v1.14, and it didn't have a problem with the existence of the `startupProbe` definition - perhaps there isn't an issue here.

**Pull request merged**
