### PR TITLE
[blocky] Improve values.yaml documentation

### PR DESCRIPTION
**Pull request by dewet22**
Also fix syntax error for declaring extraLists -- it needs to be a map, not an array

#### Special notes for your reviewer:
No functional changes, only comments reorganisation.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by billimek** [comment]
Thanks @dewet22!  Can you please bump the chart version in the Chart.yaml file?

**Comment by dewet22** [comment]
> Thanks @dewet22! Can you please bump the chart version in the Chart.yaml file?

Of course, wasn't sure whether documentation-only changes merited that.

**Comment by dewet22** [comment]
Sorry, actually bumped the wrong chart's version!

**Comment by billimek** [comment]
Indeed, no worries.  Thanks for the pull request @dewet22!

**Pull request merged**
