### PR TITLE
[home-assistant] Allow command (entrypoint) override for HA

### PR DESCRIPTION
**Pull request by dcplaya**
#### Special notes for your reviewer:
Allowed me to use a Nortek zigbee/zwave device by ser2sock and a custom configMap to run socat before HA starts. The default is disabled and also runs HA if it is enabled

Example configMap
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: zha
  namespace: home-automation
  annotations:
    fluxcd.io/ignore: false
data:
  zha: |
    #!/bin/bash
    case "$1" in
        start)
          socat pty,link=/dev/ttyZHA,raw,user=0,group=0,mode=777 tcp:ser2sock-zigbee.home-automation.svc:10000,forever,interval=10,fork &
          ;;
        stop)
          stop
          ;;
        restart)
          stop
          start
          ;;
        status)
          ;;
        *)
          echo "Usage: $0 {start|stop|status|restart}"
    esac
    exit 0
```

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by runningman84** [comment]
I think a sidecar might be a better option here?

**Comment by dcplaya** [comment]
Probably, I'm new to all of k8s. I can see if I can re-work it into a sidecar (once I actually learn what a sidecar does! :D)

**Comment by dcplaya** [comment]
Anyone have any experience sharing a `/dev` device between pods?  I shared them like one would share a volume between the two but it does not seem to like that (either HA or Kubernetes).  I am still re-working/mucking with it to see if I screwed something up but if anyone has a idea/suggestion, please chime in. 

Branch location is [here](https://github.com/dcplaya/billimek-charts/tree/HA-Sidecar), while I mess around trying to get it to work.

**Comment by jwalker343** [comment]
@dcplaya I bashed my head against doing this same thing for a week or so and eventually gave up. There is a lot of deliberate isolation around things in /dev/* as things like [/dev/mem](https://man7.org/linux/man-pages/man4/mem.4.html) exist. I eventually rolled my own docker image to get socat working, but socat was spotty and the image was tedious to maintain.

Ultimately, I deployed [zwave2mqtt](https://github.com/OpenZWave/Zwave2Mqtt) on my raspberry pi that hosts the usb controller, and then stood up an mqtt broker in Kubernetes. Works flawless, much more stable than socat/ser2net, I would highly recommend. 

If you're intent on a sidecar :), the 1.17 feature `PodShareProcessNamespace` may get you somewhere.

**Comment by dcplaya** [comment]
I had a feeling things in `/dev` were special. I haven't revisited it this week, moved on to some other charts to clear my head (got to get some wins every now and then for a moral booster). I'll check out the `PodShareProcessNamespace` but have a feeling zigbee2mqtt is going to be where I end up. And luckily someone recently added that to the HA chart! I will just have to bite the bullet and re-do some Node-Red flows, not the end of the world.

**Comment by dcplaya** [comment]
Officially giving up on this. The `PodShareProcessNamespace` is useful for this scenario but since the PID changes on each pod creation, there is no way to consistently link the two pods together. I will leave the branch active if someone wants to try again but I will be flipping to `zigbee2mqtt` and re-configuring my setup to use that instead.

**Pull request closed without merging**
