### PR TITLE
[zigbee2mqtt] ui application

### PR DESCRIPTION
**Pull request by masantiago**
#### Special notes for your reviewer:
Adding UI application to zigbee2mqtt so that both zigbee and zwave are identical in functionality
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by billimek** [comment]
Should the new `probes`, `service`, and `ingress` sections of the `values.yaml` file be encapsulated within the `ui` section?  If UI is not enabled, it doesn't seem as if they will have any use?

**Comment by masantiago** [comment]
It would be helpful that @ishioni can also have a look to the PR. I like his idea of a generic Configmap for the ui settings in [PR-294](https://github.com/billimek/billimek-charts/pull/294), although not repeating the parameters already available in the config section. That's why I eventually fixed them to prevent collision. BTW, they could be interpreted as overrides. 

As said, hopefully we can make the best of two PRs before any merge.

**Comment by elfhack** [comment]
> Should the new `probes`, `service`, and `ingress` sections of the `values.yaml` file be encapsulated within the `ui` section? If UI is not enabled, it doesn't seem as if they will have any use?

I really dislike doing it like that. In this specific instance there's not a lot of duplication (well none at all really), but usually this creates an ugly indented tag soup. Hence why my PR didn't distinguish the port and ingress options specifically for the sidecar.

**Comment by ishioni** [comment]
@masantiago 
>I like his idea of a generic Configmap for the ui settings in PR-294, although not repeating the parameters already available in the config section

You can have both. Just calculate the mqtt endpoint like you already do, set it in the configmap, then accept any other option from the config section for z2ma, and don't specify that option at all in values.yaml. You can add a comment that it's already set from z2m. If the user decides for some reason to add it anyway, it's on them, and it will work anyway, since helm doesn't deduplicate, assuming you'll loop over the options after calculating the mqtt endpoint, the user-set option will win over in the container.

**Comment by masantiago** [comment]
@ishioni agreed on all your comments and updated the code accordingly. In the latest version, you will find that I have also moved the probes, ingress and service within the assistant section. Nevertheless, only a commit revert is needed to come back to the original situation. I would be happy with any of those :smile: @billimek , please advise which option you prefer.

**Pull request merged**
