### PR TITLE
Add skipuninstall value to avoid deleting pvc upon helm uninstall

### PR DESCRIPTION
**Pull request by St0rmingBr4in**
Signed-off-by: Julien DOCHE <julien.doche@gmail.com>

This implements issue #168 by adding the `skipuninstall` value which adds the
`"helm.sh/resource-policy": keep` annotation to the created pvc.

- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by billimek** [comment]
@St0rmingBr4in, It's clearly good to provide the option to have helm skip the removal of PVCs upon deletion, but I wonder if it's too heavy-handed to make this the default behavior for these charts.

The reason I say this is that I don't see any other charts following this path and it isn't the usual expected behavior for someone removing a chart to need to do an extra clean-up step if they truly do want to remove the chart.

What do you think about making the default behavior of `skipuninstall` `false` so that a consumer of the chart can decide if they want to leverage this new feature?

**Comment by St0rmingBr4in** [comment]
Sure, I'll edit the PR. :)

**Comment by St0rmingBr4in** [comment]
Are there some other modifications needed before this can be merged ?

**Comment by billimek** [comment]
Thanks for submitting this massive change!

**Pull request merged**
