### PR TITLE
[zigbee2mqttassistant] Add chart

### PR DESCRIPTION
**Pull request by ishioni**
#### Special notes for your reviewer:
A web gui to go along with zigbee2mqtt
#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by ishioni** [comment]
Hmm, the linter failed, but wouldn't say which field it wants :/

**Comment by dcplaya** [comment]
Possible to make this a sidecar to the zigbee2mqtt chart?

**Comment by elfhack** [comment]
@dcplaya Sure it's possible. Is that the preferred way?

**Comment by onedr0p** [comment]
I would vote to add it as a sidecar to zigbee2mqtt as well @elfhack

**Comment by dcplaya** [comment]
I don't think there is a necessarily "preferred" way but since most people would never run the GUI without running the underlying zigbee2mqtt, I think it makes the most sense. More of a "1 stop shop" type of thing

**Comment by elfhack** [comment]
Fair enough. I'll get on that tommorow then :)

**Pull request closed without merging**
