### PR TITLE
[frigate] Support disabling probes and secrets for env vars

### PR DESCRIPTION
**Pull request by blakeblackshear**
#### Special notes for your reviewer:
I don't mind moving this to the frigate repo if you would prefer.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[radarr]`)

### CODE REVIEW

**Comment by blakeblackshear** [comment]
Did the GH action ever succeed for frigate?

**Comment by billimek** [comment]
Hi @blakeblackshear!  If you're willing to host the chart in the frigate repo, I would happy to contribute a PR to start that process.  The github actions for linting/testing, and releasing charts works really well IMO.  And the repo could be added to [helm hub](https://hub.helm.sh/) for better discoverability.  Let me know if you're interested!

Now, with all that said, the installation test for this chart [failed](https://github.com/billimek/billimek-charts/pull/249/checks?check_run_id=780265948) I suspect due to the fact that there isn't a real rtsp stream for frigate to connect to. Unless that can be stubbed-out somehow, it may not be possible to properly 'test' Frigate in a sanitized environment like github actions.

image

I propose we merge this given that it did pass linting and may not be possible to 'test' a full installation.

**Comment by blakeblackshear** [comment]
I'm definitely willing to host it given that is the primary way I run frigate myself.

**Comment by billimek** [comment]
Merging with failed test because it is not possible to currently test frigate without a real rtsp device available.

**Pull request merged**
